
version: '3.9'

services:
  db:
    image: mongo:5
    ports: 
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-learn
      MONGO_INITDB_ROOT_USERNAME: sebs
      MONGO_INITDB_ROOT_PASSWORD: js
    volumes:
      - mongo-data-nest3:/data/db

volumes:
  mongo-data-nest3: