image: node:11.1.0

stages:
  - install
  - test

install-dependencies:
  stage: install
  script: 
    - cd winder
      npm install
  artifact:
    expire_in: 1hr
    paths:
      - node_modules/
    cache:
      paths:
        - node_modules/


test:
  stage: test
  dependencies:
    - install-dependencies
  script:
   - npm run test:ci

   